version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nette/mail
    versions:
    - 3.1.5
  - dependency-name: nette/tokenizer
    versions:
    - 3.1.0
